version: "3.9"
services:
  app:
    build:
      context: .
    working_dir: /var/www/
    restart: always
    volumes:
      - ./src:/var/www/
    container_name: jazwacards-app
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=<insert>
    restart: always
    ports:
      - "3307:3306"
    container_name: jazwacards-db
  nginx:
    image: nginx:1.19-alpine
    working_dir: /var/www/
    volumes:
      - ./src:/var/www/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/mime.types:/etc/nginx/mime.types
    ports:
      - "8001:80"
    restart: always
    container_name: jazwacards-nginx
